<?php
/**
 * AlteracaoDesconto
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cobranças API
 *
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.17.3
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * AlteracaoDesconto Class Doc Comment
 *
 * @category Class
 * @description Alteração de desconto em Boletos Bancários
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AlteracaoDesconto implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'alteracaoDesconto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'tipo_primeiro_desconto' => 'int',
        'novo_valor_primeiro_desconto' => 'double',
        'novo_percentual_primeiro_desconto' => 'double',
        'nova_data_limite_primeiro_desconto' => 'string',
        'tipo_segundo_desconto' => 'int',
        'novo_valor_segundo_desconto' => 'double',
        'novo_percentual_segundo_desconto' => 'double',
        'nova_data_limite_segundo_desconto' => 'string',
        'tipo_terceiro_desconto' => 'int',
        'novo_valor_terceiro_desconto' => 'double',
        'novo_percentual_terceiro_desconto' => 'double',
        'nova_data_limite_terceiro_desconto' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'tipo_primeiro_desconto' => 'int32',
        'novo_valor_primeiro_desconto' => 'double',
        'novo_percentual_primeiro_desconto' => 'double',
        'nova_data_limite_primeiro_desconto' => null,
        'tipo_segundo_desconto' => 'int32',
        'novo_valor_segundo_desconto' => 'double',
        'novo_percentual_segundo_desconto' => 'double',
        'nova_data_limite_segundo_desconto' => null,
        'tipo_terceiro_desconto' => 'int32',
        'novo_valor_terceiro_desconto' => 'double',
        'novo_percentual_terceiro_desconto' => 'double',
        'nova_data_limite_terceiro_desconto' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'tipo_primeiro_desconto' => 'tipoPrimeiroDesconto',
        'novo_valor_primeiro_desconto' => 'novoValorPrimeiroDesconto',
        'novo_percentual_primeiro_desconto' => 'novoPercentualPrimeiroDesconto',
        'nova_data_limite_primeiro_desconto' => 'novaDataLimitePrimeiroDesconto',
        'tipo_segundo_desconto' => 'tipoSegundoDesconto',
        'novo_valor_segundo_desconto' => 'novoValorSegundoDesconto',
        'novo_percentual_segundo_desconto' => 'novoPercentualSegundoDesconto',
        'nova_data_limite_segundo_desconto' => 'novaDataLimiteSegundoDesconto',
        'tipo_terceiro_desconto' => 'tipoTerceiroDesconto',
        'novo_valor_terceiro_desconto' => 'novoValorTerceiroDesconto',
        'novo_percentual_terceiro_desconto' => 'novoPercentualTerceiroDesconto',
        'nova_data_limite_terceiro_desconto' => 'novaDataLimiteTerceiroDesconto'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'tipo_primeiro_desconto' => 'setTipoPrimeiroDesconto',
        'novo_valor_primeiro_desconto' => 'setNovoValorPrimeiroDesconto',
        'novo_percentual_primeiro_desconto' => 'setNovoPercentualPrimeiroDesconto',
        'nova_data_limite_primeiro_desconto' => 'setNovaDataLimitePrimeiroDesconto',
        'tipo_segundo_desconto' => 'setTipoSegundoDesconto',
        'novo_valor_segundo_desconto' => 'setNovoValorSegundoDesconto',
        'novo_percentual_segundo_desconto' => 'setNovoPercentualSegundoDesconto',
        'nova_data_limite_segundo_desconto' => 'setNovaDataLimiteSegundoDesconto',
        'tipo_terceiro_desconto' => 'setTipoTerceiroDesconto',
        'novo_valor_terceiro_desconto' => 'setNovoValorTerceiroDesconto',
        'novo_percentual_terceiro_desconto' => 'setNovoPercentualTerceiroDesconto',
        'nova_data_limite_terceiro_desconto' => 'setNovaDataLimiteTerceiroDesconto'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'tipo_primeiro_desconto' => 'getTipoPrimeiroDesconto',
        'novo_valor_primeiro_desconto' => 'getNovoValorPrimeiroDesconto',
        'novo_percentual_primeiro_desconto' => 'getNovoPercentualPrimeiroDesconto',
        'nova_data_limite_primeiro_desconto' => 'getNovaDataLimitePrimeiroDesconto',
        'tipo_segundo_desconto' => 'getTipoSegundoDesconto',
        'novo_valor_segundo_desconto' => 'getNovoValorSegundoDesconto',
        'novo_percentual_segundo_desconto' => 'getNovoPercentualSegundoDesconto',
        'nova_data_limite_segundo_desconto' => 'getNovaDataLimiteSegundoDesconto',
        'tipo_terceiro_desconto' => 'getTipoTerceiroDesconto',
        'novo_valor_terceiro_desconto' => 'getNovoValorTerceiroDesconto',
        'novo_percentual_terceiro_desconto' => 'getNovoPercentualTerceiroDesconto',
        'nova_data_limite_terceiro_desconto' => 'getNovaDataLimiteTerceiroDesconto'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['tipo_primeiro_desconto'] = isset($data['tipo_primeiro_desconto']) ? $data['tipo_primeiro_desconto'] : null;
        $this->container['novo_valor_primeiro_desconto'] = isset($data['novo_valor_primeiro_desconto']) ? $data['novo_valor_primeiro_desconto'] : null;
        $this->container['novo_percentual_primeiro_desconto'] = isset($data['novo_percentual_primeiro_desconto']) ? $data['novo_percentual_primeiro_desconto'] : null;
        $this->container['nova_data_limite_primeiro_desconto'] = isset($data['nova_data_limite_primeiro_desconto']) ? $data['nova_data_limite_primeiro_desconto'] : null;
        $this->container['tipo_segundo_desconto'] = isset($data['tipo_segundo_desconto']) ? $data['tipo_segundo_desconto'] : null;
        $this->container['novo_valor_segundo_desconto'] = isset($data['novo_valor_segundo_desconto']) ? $data['novo_valor_segundo_desconto'] : null;
        $this->container['novo_percentual_segundo_desconto'] = isset($data['novo_percentual_segundo_desconto']) ? $data['novo_percentual_segundo_desconto'] : null;
        $this->container['nova_data_limite_segundo_desconto'] = isset($data['nova_data_limite_segundo_desconto']) ? $data['nova_data_limite_segundo_desconto'] : null;
        $this->container['tipo_terceiro_desconto'] = isset($data['tipo_terceiro_desconto']) ? $data['tipo_terceiro_desconto'] : null;
        $this->container['novo_valor_terceiro_desconto'] = isset($data['novo_valor_terceiro_desconto']) ? $data['novo_valor_terceiro_desconto'] : null;
        $this->container['novo_percentual_terceiro_desconto'] = isset($data['novo_percentual_terceiro_desconto']) ? $data['novo_percentual_terceiro_desconto'] : null;
        $this->container['nova_data_limite_terceiro_desconto'] = isset($data['nova_data_limite_terceiro_desconto']) ? $data['nova_data_limite_terceiro_desconto'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets tipo_primeiro_desconto
     *
     * @return int
     */
    public function getTipoPrimeiroDesconto()
    {
        return $this->container['tipo_primeiro_desconto'];
    }

    /**
     * Sets tipo_primeiro_desconto
     *
     * @param int $tipo_primeiro_desconto Código para identificação do tipo de desconto que deverá ser concedido como Primeiro Desconto. Valores a informar: 0 - Sem desconto 1 - Valor fixo até a data 2 - Percentual até a data informada 3 - Desconto por dia de antecipação
     *
     * @return $this
     */
    public function setTipoPrimeiroDesconto($tipo_primeiro_desconto)
    {
        $this->container['tipo_primeiro_desconto'] = $tipo_primeiro_desconto;

        return $this;
    }

    /**
     * Gets novo_valor_primeiro_desconto
     *
     * @return double
     */
    public function getNovoValorPrimeiroDesconto()
    {
        return $this->container['novo_valor_primeiro_desconto'];
    }

    /**
     * Sets novo_valor_primeiro_desconto
     *
     * @param double $novo_valor_primeiro_desconto Novo valor do Primeiro Desconto
     *
     * @return $this
     */
    public function setNovoValorPrimeiroDesconto($novo_valor_primeiro_desconto)
    {
        $this->container['novo_valor_primeiro_desconto'] = $novo_valor_primeiro_desconto;

        return $this;
    }

    /**
     * Gets novo_percentual_primeiro_desconto
     *
     * @return double
     */
    public function getNovoPercentualPrimeiroDesconto()
    {
        return $this->container['novo_percentual_primeiro_desconto'];
    }

    /**
     * Sets novo_percentual_primeiro_desconto
     *
     * @param double $novo_percentual_primeiro_desconto Novo percentual de desconto sobre o valor do boleto no Primeiro Desconto
     *
     * @return $this
     */
    public function setNovoPercentualPrimeiroDesconto($novo_percentual_primeiro_desconto)
    {
        $this->container['novo_percentual_primeiro_desconto'] = $novo_percentual_primeiro_desconto;

        return $this;
    }

    /**
     * Gets nova_data_limite_primeiro_desconto
     *
     * @return string
     */
    public function getNovaDataLimitePrimeiroDesconto()
    {
        return $this->container['nova_data_limite_primeiro_desconto'];
    }

    /**
     * Sets nova_data_limite_primeiro_desconto
     *
     * @param string $nova_data_limite_primeiro_desconto Nova data limite do Primeiro Desconto
     *
     * @return $this
     */
    public function setNovaDataLimitePrimeiroDesconto($nova_data_limite_primeiro_desconto)
    {
        $this->container['nova_data_limite_primeiro_desconto'] = $nova_data_limite_primeiro_desconto;

        return $this;
    }

    /**
     * Gets tipo_segundo_desconto
     *
     * @return int
     */
    public function getTipoSegundoDesconto()
    {
        return $this->container['tipo_segundo_desconto'];
    }

    /**
     * Sets tipo_segundo_desconto
     *
     * @param int $tipo_segundo_desconto Código para identificação do tipo de desconto que deverá ser concedido como Segundo Desconto. Valores a informar: 0 - Sem desconto 1 - Valor fixo até a data 2 - Percentual até a data informada 3 - Desconto por dia de antecipação
     *
     * @return $this
     */
    public function setTipoSegundoDesconto($tipo_segundo_desconto)
    {
        $this->container['tipo_segundo_desconto'] = $tipo_segundo_desconto;

        return $this;
    }

    /**
     * Gets novo_valor_segundo_desconto
     *
     * @return double
     */
    public function getNovoValorSegundoDesconto()
    {
        return $this->container['novo_valor_segundo_desconto'];
    }

    /**
     * Sets novo_valor_segundo_desconto
     *
     * @param double $novo_valor_segundo_desconto Novo valor do Segundo Desconto
     *
     * @return $this
     */
    public function setNovoValorSegundoDesconto($novo_valor_segundo_desconto)
    {
        $this->container['novo_valor_segundo_desconto'] = $novo_valor_segundo_desconto;

        return $this;
    }

    /**
     * Gets novo_percentual_segundo_desconto
     *
     * @return double
     */
    public function getNovoPercentualSegundoDesconto()
    {
        return $this->container['novo_percentual_segundo_desconto'];
    }

    /**
     * Sets novo_percentual_segundo_desconto
     *
     * @param double $novo_percentual_segundo_desconto Novo percentual de desconto sobre o valor do boleto no Segundo Desconto
     *
     * @return $this
     */
    public function setNovoPercentualSegundoDesconto($novo_percentual_segundo_desconto)
    {
        $this->container['novo_percentual_segundo_desconto'] = $novo_percentual_segundo_desconto;

        return $this;
    }

    /**
     * Gets nova_data_limite_segundo_desconto
     *
     * @return string
     */
    public function getNovaDataLimiteSegundoDesconto()
    {
        return $this->container['nova_data_limite_segundo_desconto'];
    }

    /**
     * Sets nova_data_limite_segundo_desconto
     *
     * @param string $nova_data_limite_segundo_desconto Nova data limite do Segundo Desconto
     *
     * @return $this
     */
    public function setNovaDataLimiteSegundoDesconto($nova_data_limite_segundo_desconto)
    {
        $this->container['nova_data_limite_segundo_desconto'] = $nova_data_limite_segundo_desconto;

        return $this;
    }

    /**
     * Gets tipo_terceiro_desconto
     *
     * @return int
     */
    public function getTipoTerceiroDesconto()
    {
        return $this->container['tipo_terceiro_desconto'];
    }

    /**
     * Sets tipo_terceiro_desconto
     *
     * @param int $tipo_terceiro_desconto Código para identificação do tipo de desconto que deverá ser concedido como Terceiro Desconto. Valores a informar: 0 - Sem desconto 1 - Valor fixo até a data 2 - Percentual até a data informada 3 - Desconto por dia de antecipação
     *
     * @return $this
     */
    public function setTipoTerceiroDesconto($tipo_terceiro_desconto)
    {
        $this->container['tipo_terceiro_desconto'] = $tipo_terceiro_desconto;

        return $this;
    }

    /**
     * Gets novo_valor_terceiro_desconto
     *
     * @return double
     */
    public function getNovoValorTerceiroDesconto()
    {
        return $this->container['novo_valor_terceiro_desconto'];
    }

    /**
     * Sets novo_valor_terceiro_desconto
     *
     * @param double $novo_valor_terceiro_desconto Novo valor do Terceiro Desconto
     *
     * @return $this
     */
    public function setNovoValorTerceiroDesconto($novo_valor_terceiro_desconto)
    {
        $this->container['novo_valor_terceiro_desconto'] = $novo_valor_terceiro_desconto;

        return $this;
    }

    /**
     * Gets novo_percentual_terceiro_desconto
     *
     * @return double
     */
    public function getNovoPercentualTerceiroDesconto()
    {
        return $this->container['novo_percentual_terceiro_desconto'];
    }

    /**
     * Sets novo_percentual_terceiro_desconto
     *
     * @param double $novo_percentual_terceiro_desconto Novo percentual de desconto sobre o valor do boleto no Terceiro Desconto
     *
     * @return $this
     */
    public function setNovoPercentualTerceiroDesconto($novo_percentual_terceiro_desconto)
    {
        $this->container['novo_percentual_terceiro_desconto'] = $novo_percentual_terceiro_desconto;

        return $this;
    }

    /**
     * Gets nova_data_limite_terceiro_desconto
     *
     * @return string
     */
    public function getNovaDataLimiteTerceiroDesconto()
    {
        return $this->container['nova_data_limite_terceiro_desconto'];
    }

    /**
     * Sets nova_data_limite_terceiro_desconto
     *
     * @param string $nova_data_limite_terceiro_desconto Nova data limite do Terceiro Desconto
     *
     * @return $this
     */
    public function setNovaDataLimiteTerceiroDesconto($nova_data_limite_terceiro_desconto)
    {
        $this->container['nova_data_limite_terceiro_desconto'] = $nova_data_limite_terceiro_desconto;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
