<?php
/**
 * InlineResponse2001
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cobranças API
 *
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.17.3
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * InlineResponse2001 Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2001 implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'inline_response_200_1';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'indicador_continuidade' => 'string',
        'numero_ultimo_registro' => 'int',
        'lista_registro' => '\Swagger\Client\Model\InlineResponse2001ListaRegistro[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'indicador_continuidade' => null,
        'numero_ultimo_registro' => 'int64',
        'lista_registro' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'indicador_continuidade' => 'indicadorContinuidade',
        'numero_ultimo_registro' => 'numeroUltimoRegistro',
        'lista_registro' => 'listaRegistro'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'indicador_continuidade' => 'setIndicadorContinuidade',
        'numero_ultimo_registro' => 'setNumeroUltimoRegistro',
        'lista_registro' => 'setListaRegistro'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'indicador_continuidade' => 'getIndicadorContinuidade',
        'numero_ultimo_registro' => 'getNumeroUltimoRegistro',
        'lista_registro' => 'getListaRegistro'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const INDICADOR_CONTINUIDADE_S = 'S';
    const INDICADOR_CONTINUIDADE_N = 'N';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getIndicadorContinuidadeAllowableValues()
    {
        return [
            self::INDICADOR_CONTINUIDADE_S,
            self::INDICADOR_CONTINUIDADE_N,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['indicador_continuidade'] = isset($data['indicador_continuidade']) ? $data['indicador_continuidade'] : null;
        $this->container['numero_ultimo_registro'] = isset($data['numero_ultimo_registro']) ? $data['numero_ultimo_registro'] : null;
        $this->container['lista_registro'] = isset($data['lista_registro']) ? $data['lista_registro'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getIndicadorContinuidadeAllowableValues();
        if (!is_null($this->container['indicador_continuidade']) && !in_array($this->container['indicador_continuidade'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'indicador_continuidade', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets indicador_continuidade
     *
     * @return string
     */
    public function getIndicadorContinuidade()
    {
        return $this->container['indicador_continuidade'];
    }

    /**
     * Sets indicador_continuidade
     *
     * @param string $indicador_continuidade Indicador de continuidade para informar que a pesquisa possui mais registros a apresentar S-Sim, N-Não
     *
     * @return $this
     */
    public function setIndicadorContinuidade($indicador_continuidade)
    {
        $allowedValues = $this->getIndicadorContinuidadeAllowableValues();
        if (!is_null($indicador_continuidade) && !in_array($indicador_continuidade, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'indicador_continuidade', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['indicador_continuidade'] = $indicador_continuidade;

        return $this;
    }

    /**
     * Gets numero_ultimo_registro
     *
     * @return int
     */
    public function getNumeroUltimoRegistro()
    {
        return $this->container['numero_ultimo_registro'];
    }

    /**
     * Sets numero_ultimo_registro
     *
     * @param int $numero_ultimo_registro Numero do ultimo registro da consulta
     *
     * @return $this
     */
    public function setNumeroUltimoRegistro($numero_ultimo_registro)
    {
        $this->container['numero_ultimo_registro'] = $numero_ultimo_registro;

        return $this;
    }

    /**
     * Gets lista_registro
     *
     * @return \Swagger\Client\Model\InlineResponse2001ListaRegistro[]
     */
    public function getListaRegistro()
    {
        return $this->container['lista_registro'];
    }

    /**
     * Sets lista_registro
     *
     * @param \Swagger\Client\Model\InlineResponse2001ListaRegistro[] $lista_registro lista_registro
     *
     * @return $this
     */
    public function setListaRegistro($lista_registro)
    {
        $this->container['lista_registro'] = $lista_registro;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
