<?php
/**
 * Multa
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cobranças API
 *
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.17.3
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * Multa Class Doc Comment
 *
 * @category Class
 * @description Inclusão de multa em Boleto Bancário
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Multa implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'multa';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'tipo_multa' => 'int',
        'valor_multa' => 'float',
        'data_inicio_multa' => 'string',
        'taxa_multa' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'tipo_multa' => 'int32',
        'valor_multa' => 'float',
        'data_inicio_multa' => null,
        'taxa_multa' => 'float'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'tipo_multa' => 'tipoMulta',
        'valor_multa' => 'valorMulta',
        'data_inicio_multa' => 'dataInicioMulta',
        'taxa_multa' => 'taxaMulta'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'tipo_multa' => 'setTipoMulta',
        'valor_multa' => 'setValorMulta',
        'data_inicio_multa' => 'setDataInicioMulta',
        'taxa_multa' => 'setTaxaMulta'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'tipo_multa' => 'getTipoMulta',
        'valor_multa' => 'getValorMulta',
        'data_inicio_multa' => 'getDataInicioMulta',
        'taxa_multa' => 'getTaxaMulta'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['tipo_multa'] = isset($data['tipo_multa']) ? $data['tipo_multa'] : null;
        $this->container['valor_multa'] = isset($data['valor_multa']) ? $data['valor_multa'] : null;
        $this->container['data_inicio_multa'] = isset($data['data_inicio_multa']) ? $data['data_inicio_multa'] : null;
        $this->container['taxa_multa'] = isset($data['taxa_multa']) ? $data['taxa_multa'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets tipo_multa
     *
     * @return int
     */
    public function getTipoMulta()
    {
        return $this->container['tipo_multa'];
    }

    /**
     * Sets tipo_multa
     *
     * @param int $tipo_multa Porcentagem sobre o valor do boleto a ser cobrada de multa
     *
     * @return $this
     */
    public function setTipoMulta($tipo_multa)
    {
        $this->container['tipo_multa'] = $tipo_multa;

        return $this;
    }

    /**
     * Gets valor_multa
     *
     * @return float
     */
    public function getValorMulta()
    {
        return $this->container['valor_multa'];
    }

    /**
     * Sets valor_multa
     *
     * @param float $valor_multa Data para início da cobrança da multa
     *
     * @return $this
     */
    public function setValorMulta($valor_multa)
    {
        $this->container['valor_multa'] = $valor_multa;

        return $this;
    }

    /**
     * Gets data_inicio_multa
     *
     * @return string
     */
    public function getDataInicioMulta()
    {
        return $this->container['data_inicio_multa'];
    }

    /**
     * Sets data_inicio_multa
     *
     * @param string $data_inicio_multa Código para identificação do tipo de multa
     *
     * @return $this
     */
    public function setDataInicioMulta($data_inicio_multa)
    {
        $this->container['data_inicio_multa'] = $data_inicio_multa;

        return $this;
    }

    /**
     * Gets taxa_multa
     *
     * @return float
     */
    public function getTaxaMulta()
    {
        return $this->container['taxa_multa'];
    }

    /**
     * Sets taxa_multa
     *
     * @param float $taxa_multa Valor  sobre o valor do boleto a ser cobrado de multa
     *
     * @return $this
     */
    public function setTaxaMulta($taxa_multa)
    {
        $this->container['taxa_multa'] = $taxa_multa;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
