<?php
/**
 * RespostaBoletosBaixaOperacionalTitulo
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cobranças API
 *
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.17.3
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Boleto\Model;

use \ArrayAccess;
use \Swagger\Client\Boleto\ObjectSerializer;

/**
 * RespostaBoletosBaixaOperacionalTitulo Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RespostaBoletosBaixaOperacionalTitulo implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'RespostaBoletosBaixaOperacional_titulo';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'string',
        'estado_baixa_operacional' => 'int',
        'modalidade' => 'int',
        'data_registro' => 'string',
        'data_vencimento' => 'string',
        'valor_original' => 'double',
        'agendamento_pagamento' => '\Swagger\Client\Boleto\Model\RespostaBoletosBaixaOperacionalTituloAgendamentoPagamento'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => null,
        'estado_baixa_operacional' => 'int32',
        'modalidade' => 'int32',
        'data_registro' => null,
        'data_vencimento' => null,
        'valor_original' => 'double',
        'agendamento_pagamento' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'estado_baixa_operacional' => 'estadoBaixaOperacional',
        'modalidade' => 'modalidade',
        'data_registro' => 'dataRegistro',
        'data_vencimento' => 'dataVencimento',
        'valor_original' => 'valorOriginal',
        'agendamento_pagamento' => 'agendamentoPagamento'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'estado_baixa_operacional' => 'setEstadoBaixaOperacional',
        'modalidade' => 'setModalidade',
        'data_registro' => 'setDataRegistro',
        'data_vencimento' => 'setDataVencimento',
        'valor_original' => 'setValorOriginal',
        'agendamento_pagamento' => 'setAgendamentoPagamento'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'estado_baixa_operacional' => 'getEstadoBaixaOperacional',
        'modalidade' => 'getModalidade',
        'data_registro' => 'getDataRegistro',
        'data_vencimento' => 'getDataVencimento',
        'valor_original' => 'getValorOriginal',
        'agendamento_pagamento' => 'getAgendamentoPagamento'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['estado_baixa_operacional'] = isset($data['estado_baixa_operacional']) ? $data['estado_baixa_operacional'] : null;
        $this->container['modalidade'] = isset($data['modalidade']) ? $data['modalidade'] : null;
        $this->container['data_registro'] = isset($data['data_registro']) ? $data['data_registro'] : null;
        $this->container['data_vencimento'] = isset($data['data_vencimento']) ? $data['data_vencimento'] : null;
        $this->container['valor_original'] = isset($data['valor_original']) ? $data['valor_original'] : null;
        $this->container['agendamento_pagamento'] = isset($data['agendamento_pagamento']) ? $data['agendamento_pagamento'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id Número de identificação do boleto (correspondente ao NOSSO NÚMERO, numeroTituloCliente), cujo conteúdo é composto de: \"000\" + (número do convênio com 7 dígitos) + (10 algarismos - se necessário, completar com zeros à esquerda).
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets estado_baixa_operacional
     *
     * @return int
     */
    public function getEstadoBaixaOperacional()
    {
        return $this->container['estado_baixa_operacional'];
    }

    /**
     * Sets estado_baixa_operacional
     *
     * @param int $estado_baixa_operacional Código para identificar o estado da baixa operacional.  Domínio: 1 - BAIXA OPERACIONAL BB 2 - BAIXA OPERACIONAL OUTROS BANCOS 10- CANCELAMENTO DE BAIXA OPERACIONAL
     *
     * @return $this
     */
    public function setEstadoBaixaOperacional($estado_baixa_operacional)
    {
        $this->container['estado_baixa_operacional'] = $estado_baixa_operacional;

        return $this;
    }

    /**
     * Gets modalidade
     *
     * @return int
     */
    public function getModalidade()
    {
        return $this->container['modalidade'];
    }

    /**
     * Sets modalidade
     *
     * @param int $modalidade Código para identificar a característica dos boletos dentro das modalidades de cobrança existentes no banco.  Domínio: 1 - SIMPLES 4 - VINCULADA
     *
     * @return $this
     */
    public function setModalidade($modalidade)
    {
        $this->container['modalidade'] = $modalidade;

        return $this;
    }

    /**
     * Gets data_registro
     *
     * @return string
     */
    public function getDataRegistro()
    {
        return $this->container['data_registro'];
    }

    /**
     * Sets data_registro
     *
     * @param string $data_registro Data a qual foi efetuado o registro do boleto na CIP.
     *
     * @return $this
     */
    public function setDataRegistro($data_registro)
    {
        $this->container['data_registro'] = $data_registro;

        return $this;
    }

    /**
     * Gets data_vencimento
     *
     * @return string
     */
    public function getDataVencimento()
    {
        return $this->container['data_vencimento'];
    }

    /**
     * Sets data_vencimento
     *
     * @param string $data_vencimento Data de vencimento do boleto.
     *
     * @return $this
     */
    public function setDataVencimento($data_vencimento)
    {
        $this->container['data_vencimento'] = $data_vencimento;

        return $this;
    }

    /**
     * Gets valor_original
     *
     * @return double
     */
    public function getValorOriginal()
    {
        return $this->container['valor_original'];
    }

    /**
     * Sets valor_original
     *
     * @param double $valor_original Valor original do boleto indicado quando do registro.
     *
     * @return $this
     */
    public function setValorOriginal($valor_original)
    {
        $this->container['valor_original'] = $valor_original;

        return $this;
    }

    /**
     * Gets agendamento_pagamento
     *
     * @return \Swagger\Client\Boleto\Model\RespostaBoletosBaixaOperacionalTituloAgendamentoPagamento
     */
    public function getAgendamentoPagamento()
    {
        return $this->container['agendamento_pagamento'];
    }

    /**
     * Sets agendamento_pagamento
     *
     * @param \Swagger\Client\Boleto\Model\RespostaBoletosBaixaOperacionalTituloAgendamentoPagamento $agendamento_pagamento agendamento_pagamento
     *
     * @return $this
     */
    public function setAgendamentoPagamento($agendamento_pagamento)
    {
        $this->container['agendamento_pagamento'] = $agendamento_pagamento;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
