<?php
/**
 * RespostaAlterarBoleto
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cobranças API
 *
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.17.3
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Boleto\Model;

use \ArrayAccess;
use \Swagger\Client\Boleto\ObjectSerializer;

/**
 * RespostaAlterarBoleto Class Doc Comment
 *
 * @category Class
 * @description Representação dos campos de resposta de uma solicitação de alteração dos dados de boletos bancários.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RespostaAlterarBoleto implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'RespostaAlterarBoleto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'numero_contrato_cobranca' => 'int',
        'data_atualizacao' => 'string',
        'horario_atualizacao' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'numero_contrato_cobranca' => 'int32',
        'data_atualizacao' => null,
        'horario_atualizacao' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'numero_contrato_cobranca' => 'numeroContratoCobranca',
        'data_atualizacao' => 'dataAtualizacao',
        'horario_atualizacao' => 'horarioAtualizacao'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'numero_contrato_cobranca' => 'setNumeroContratoCobranca',
        'data_atualizacao' => 'setDataAtualizacao',
        'horario_atualizacao' => 'setHorarioAtualizacao'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'numero_contrato_cobranca' => 'getNumeroContratoCobranca',
        'data_atualizacao' => 'getDataAtualizacao',
        'horario_atualizacao' => 'getHorarioAtualizacao'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['numero_contrato_cobranca'] = isset($data['numero_contrato_cobranca']) ? $data['numero_contrato_cobranca'] : null;
        $this->container['data_atualizacao'] = isset($data['data_atualizacao']) ? $data['data_atualizacao'] : null;
        $this->container['horario_atualizacao'] = isset($data['horario_atualizacao']) ? $data['horario_atualizacao'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets numero_contrato_cobranca
     *
     * @return int
     */
    public function getNumeroContratoCobranca()
    {
        return $this->container['numero_contrato_cobranca'];
    }

    /**
     * Sets numero_contrato_cobranca
     *
     * @param int $numero_contrato_cobranca Código adotado pelo Banco para identificar o Contrato entre este e a Empresa Cliente
     *
     * @return $this
     */
    public function setNumeroContratoCobranca($numero_contrato_cobranca)
    {
        $this->container['numero_contrato_cobranca'] = $numero_contrato_cobranca;

        return $this;
    }

    /**
     * Gets data_atualizacao
     *
     * @return string
     */
    public function getDataAtualizacao()
    {
        return $this->container['data_atualizacao'];
    }

    /**
     * Sets data_atualizacao
     *
     * @param string $data_atualizacao Data do pedido de atualização do boleto bancário.
     *
     * @return $this
     */
    public function setDataAtualizacao($data_atualizacao)
    {
        $this->container['data_atualizacao'] = $data_atualizacao;

        return $this;
    }

    /**
     * Gets horario_atualizacao
     *
     * @return string
     */
    public function getHorarioAtualizacao()
    {
        return $this->container['horario_atualizacao'];
    }

    /**
     * Sets horario_atualizacao
     *
     * @param string $horario_atualizacao Horário do pedido de atualização do boleto bancário.HH:mm:ss
     *
     * @return $this
     */
    public function setHorarioAtualizacao($horario_atualizacao)
    {
        $this->container['horario_atualizacao'] = $horario_atualizacao;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
