<?php
/**
 * RespostaListaBoletos
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cobranças API
 *
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.17.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * RespostaListaBoletos Class Doc Comment
 *
 * @category Class
 * @description Objeto de Resposta do recurso GET Lista Boletos
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RespostaListaBoletos implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'RespostaListaBoletos';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'indicador_continuidade' => 'string',
        'quantidade_registros' => 'int',
        'proximo_indice' => 'int',
        'boletos' => '\Swagger\Client\Model\RespostaListaBoletosBoletos[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'indicador_continuidade' => null,
        'quantidade_registros' => 'int32',
        'proximo_indice' => 'int32',
        'boletos' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'indicador_continuidade' => 'indicadorContinuidade',
        'quantidade_registros' => 'quantidadeRegistros',
        'proximo_indice' => 'proximoIndice',
        'boletos' => 'boletos'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'indicador_continuidade' => 'setIndicadorContinuidade',
        'quantidade_registros' => 'setQuantidadeRegistros',
        'proximo_indice' => 'setProximoIndice',
        'boletos' => 'setBoletos'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'indicador_continuidade' => 'getIndicadorContinuidade',
        'quantidade_registros' => 'getQuantidadeRegistros',
        'proximo_indice' => 'getProximoIndice',
        'boletos' => 'getBoletos'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['indicador_continuidade'] = isset($data['indicador_continuidade']) ? $data['indicador_continuidade'] : null;
        $this->container['quantidade_registros'] = isset($data['quantidade_registros']) ? $data['quantidade_registros'] : null;
        $this->container['proximo_indice'] = isset($data['proximo_indice']) ? $data['proximo_indice'] : null;
        $this->container['boletos'] = isset($data['boletos']) ? $data['boletos'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets indicador_continuidade
     *
     * @return string
     */
    public function getIndicadorContinuidade()
    {
        return $this->container['indicador_continuidade'];
    }

    /**
     * Sets indicador_continuidade
     *
     * @param string $indicador_continuidade Indicador de que a consulta resultou em uma quantidade superior a 300 boletos (capacidade de resposta por requisição do serviço). Uma nova requisição, nos mesmos moldes, deve ser feita para consultar o restante dos boletos. Para tanto, deverá ser utilizado o valor informado no atributo \"Número Último Registro\" como valor inicial da próxima consulta.
     *
     * @return $this
     */
    public function setIndicadorContinuidade($indicador_continuidade)
    {
        $this->container['indicador_continuidade'] = $indicador_continuidade;

        return $this;
    }

    /**
     * Gets quantidade_registros
     *
     * @return int
     */
    public function getQuantidadeRegistros()
    {
        return $this->container['quantidade_registros'];
    }

    /**
     * Sets quantidade_registros
     *
     * @param int $quantidade_registros Quantidade de boletos que atendem os critérios da requisição.
     *
     * @return $this
     */
    public function setQuantidadeRegistros($quantidade_registros)
    {
        $this->container['quantidade_registros'] = $quantidade_registros;

        return $this;
    }

    /**
     * Gets proximo_indice
     *
     * @return int
     */
    public function getProximoIndice()
    {
        return $this->container['proximo_indice'];
    }

    /**
     * Sets proximo_indice
     *
     * @param int $proximo_indice Número do último registro apresentado pela lista, que poderá ser utilizado como parâmetro inicial de uma nova requisição para consultar os boletos restantes.
     *
     * @return $this
     */
    public function setProximoIndice($proximo_indice)
    {
        $this->container['proximo_indice'] = $proximo_indice;

        return $this;
    }

    /**
     * Gets boletos
     *
     * @return \Swagger\Client\Model\RespostaListaBoletosBoletos[]
     */
    public function getBoletos()
    {
        return $this->container['boletos'];
    }

    /**
     * Sets boletos
     *
     * @param \Swagger\Client\Model\RespostaListaBoletosBoletos[] $boletos boletos
     *
     * @return $this
     */
    public function setBoletos($boletos)
    {
        $this->container['boletos'] = $boletos;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
