<?php
/**
 * Errov2ErrosTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cobranças API
 *
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.17.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * Errov2ErrosTest Class Doc Comment
 *
 * @category    Class
 * @description Errov2Erros
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Errov2ErrosTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Errov2Erros"
     */
    public function testErrov2Erros()
    {
    }

    /**
     * Test attribute "codigo_mensagem"
     */
    public function testPropertyCodigoMensagem()
    {
    }

    /**
     * Test attribute "versao_mensagem"
     */
    public function testPropertyVersaoMensagem()
    {
    }

    /**
     * Test attribute "texto_mensagem"
     */
    public function testPropertyTextoMensagem()
    {
    }

    /**
     * Test attribute "codigo_retorno"
     */
    public function testPropertyCodigoRetorno()
    {
    }
}
