<?php
/**
 * RespostaConsultaPixBoletoPixTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cobranças API
 *
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.17.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * RespostaConsultaPixBoletoPixTest Class Doc Comment
 *
 * @category    Class
 * @description RespostaConsultaPixBoletoPix
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RespostaConsultaPixBoletoPixTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "RespostaConsultaPixBoletoPix"
     */
    public function testRespostaConsultaPixBoletoPix()
    {
    }

    /**
     * Test attribute "valor_recebido"
     */
    public function testPropertyValorRecebido()
    {
    }

    /**
     * Test attribute "timestamp"
     */
    public function testPropertyTimestamp()
    {
    }

    /**
     * Test attribute "chave"
     */
    public function testPropertyChave()
    {
    }

    /**
     * Test attribute "texto_retorno"
     */
    public function testPropertyTextoRetorno()
    {
    }

    /**
     * Test attribute "id_instituicao_pagador"
     */
    public function testPropertyIdInstituicaoPagador()
    {
    }

    /**
     * Test attribute "agencia_pagador"
     */
    public function testPropertyAgenciaPagador()
    {
    }

    /**
     * Test attribute "conta_pagador"
     */
    public function testPropertyContaPagador()
    {
    }

    /**
     * Test attribute "tipo_pessoa_pagador"
     */
    public function testPropertyTipoPessoaPagador()
    {
    }

    /**
     * Test attribute "id_pagador"
     */
    public function testPropertyIdPagador()
    {
    }
}
