<?php
/**
 * RespostaBaixaBoletoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cobranças API
 *
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.17.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * RespostaBaixaBoletoTest Class Doc Comment
 *
 * @category    Class
 * @description Objeto de resposta da baixa de boletos.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RespostaBaixaBoletoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "RespostaBaixaBoleto"
     */
    public function testRespostaBaixaBoleto()
    {
    }

    /**
     * Test attribute "numero_contrato_cobranca"
     */
    public function testPropertyNumeroContratoCobranca()
    {
    }

    /**
     * Test attribute "data_baixa"
     */
    public function testPropertyDataBaixa()
    {
    }

    /**
     * Test attribute "horario_baixa"
     */
    public function testPropertyHorarioBaixa()
    {
    }
}
