<?php
/**
 * RespostaRegistroBoletosTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cobranças API
 *
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.17.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * RespostaRegistroBoletosTest Class Doc Comment
 *
 * @category    Class
 * @description Representação dos campos de resposta de uma solicitação de criação de boletos bancários.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RespostaRegistroBoletosTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "RespostaRegistroBoletos"
     */
    public function testRespostaRegistroBoletos()
    {
    }

    /**
     * Test attribute "numero"
     */
    public function testPropertyNumero()
    {
    }

    /**
     * Test attribute "numero_carteira"
     */
    public function testPropertyNumeroCarteira()
    {
    }

    /**
     * Test attribute "numero_variacao_carteira"
     */
    public function testPropertyNumeroVariacaoCarteira()
    {
    }

    /**
     * Test attribute "codigo_cliente"
     */
    public function testPropertyCodigoCliente()
    {
    }

    /**
     * Test attribute "linha_digitavel"
     */
    public function testPropertyLinhaDigitavel()
    {
    }

    /**
     * Test attribute "codigo_barra_numerico"
     */
    public function testPropertyCodigoBarraNumerico()
    {
    }

    /**
     * Test attribute "numero_contrato_cobranca"
     */
    public function testPropertyNumeroContratoCobranca()
    {
    }

    /**
     * Test attribute "beneficiario"
     */
    public function testPropertyBeneficiario()
    {
    }

    /**
     * Test attribute "qr_code"
     */
    public function testPropertyQrCode()
    {
    }

    /**
     * Test attribute "observacao"
     */
    public function testPropertyObservacao()
    {
    }
}
