<?php
/**
 * RespostaListaBoletosBoletosTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cobranças API
 *
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.17.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * RespostaListaBoletosBoletosTest Class Doc Comment
 *
 * @category    Class
 * @description RespostaListaBoletosBoletos
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RespostaListaBoletosBoletosTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "RespostaListaBoletosBoletos"
     */
    public function testRespostaListaBoletosBoletos()
    {
    }

    /**
     * Test attribute "numero_boleto_bb"
     */
    public function testPropertyNumeroBoletoBb()
    {
    }

    /**
     * Test attribute "estado_titulo_cobranca"
     */
    public function testPropertyEstadoTituloCobranca()
    {
    }

    /**
     * Test attribute "data_registro"
     */
    public function testPropertyDataRegistro()
    {
    }

    /**
     * Test attribute "data_vencimento"
     */
    public function testPropertyDataVencimento()
    {
    }

    /**
     * Test attribute "data_movimento"
     */
    public function testPropertyDataMovimento()
    {
    }

    /**
     * Test attribute "valor_original"
     */
    public function testPropertyValorOriginal()
    {
    }

    /**
     * Test attribute "valor_atual"
     */
    public function testPropertyValorAtual()
    {
    }

    /**
     * Test attribute "valor_pago"
     */
    public function testPropertyValorPago()
    {
    }

    /**
     * Test attribute "contrato"
     */
    public function testPropertyContrato()
    {
    }

    /**
     * Test attribute "carteira_convenio"
     */
    public function testPropertyCarteiraConvenio()
    {
    }

    /**
     * Test attribute "variacao_carteira_convenio"
     */
    public function testPropertyVariacaoCarteiraConvenio()
    {
    }

    /**
     * Test attribute "codigo_estado_titulo_cobranca"
     */
    public function testPropertyCodigoEstadoTituloCobranca()
    {
    }

    /**
     * Test attribute "data_credito"
     */
    public function testPropertyDataCredito()
    {
    }
}
