<?php
/**
 * RespostaDetalhamentoBoletoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cobranças API
 *
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.17.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * RespostaDetalhamentoBoletoTest Class Doc Comment
 *
 * @category    Class
 * @description Representação dos campos de resposta de uma solicitação de detalhamento de boletos bancários.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RespostaDetalhamentoBoletoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "RespostaDetalhamentoBoleto"
     */
    public function testRespostaDetalhamentoBoleto()
    {
    }

    /**
     * Test attribute "codigo_linha_digitavel"
     */
    public function testPropertyCodigoLinhaDigitavel()
    {
    }

    /**
     * Test attribute "texto_email_pagador"
     */
    public function testPropertyTextoEmailPagador()
    {
    }

    /**
     * Test attribute "texto_mensagem_bloqueto_titulo"
     */
    public function testPropertyTextoMensagemBloquetoTitulo()
    {
    }

    /**
     * Test attribute "codigo_tipo_multa"
     */
    public function testPropertyCodigoTipoMulta()
    {
    }

    /**
     * Test attribute "codigo_canal_pagamento"
     */
    public function testPropertyCodigoCanalPagamento()
    {
    }

    /**
     * Test attribute "numero_contrato_cobranca"
     */
    public function testPropertyNumeroContratoCobranca()
    {
    }

    /**
     * Test attribute "codigo_tipo_inscricao_sacado"
     */
    public function testPropertyCodigoTipoInscricaoSacado()
    {
    }

    /**
     * Test attribute "numero_inscricao_sacado_cobranca"
     */
    public function testPropertyNumeroInscricaoSacadoCobranca()
    {
    }

    /**
     * Test attribute "codigo_estado_titulo_cobranca"
     */
    public function testPropertyCodigoEstadoTituloCobranca()
    {
    }

    /**
     * Test attribute "codigo_tipo_titulo_cobranca"
     */
    public function testPropertyCodigoTipoTituloCobranca()
    {
    }

    /**
     * Test attribute "codigo_modalidade_titulo"
     */
    public function testPropertyCodigoModalidadeTitulo()
    {
    }

    /**
     * Test attribute "codigo_aceite_titulo_cobranca"
     */
    public function testPropertyCodigoAceiteTituloCobranca()
    {
    }

    /**
     * Test attribute "codigo_prefixo_dependencia_cobrador"
     */
    public function testPropertyCodigoPrefixoDependenciaCobrador()
    {
    }

    /**
     * Test attribute "codigo_indicador_economico"
     */
    public function testPropertyCodigoIndicadorEconomico()
    {
    }

    /**
     * Test attribute "numero_titulo_cedente_cobranca"
     */
    public function testPropertyNumeroTituloCedenteCobranca()
    {
    }

    /**
     * Test attribute "codigo_tipo_juro_mora"
     */
    public function testPropertyCodigoTipoJuroMora()
    {
    }

    /**
     * Test attribute "data_emissao_titulo_cobranca"
     */
    public function testPropertyDataEmissaoTituloCobranca()
    {
    }

    /**
     * Test attribute "data_registro_titulo_cobranca"
     */
    public function testPropertyDataRegistroTituloCobranca()
    {
    }

    /**
     * Test attribute "data_vencimento_titulo_cobranca"
     */
    public function testPropertyDataVencimentoTituloCobranca()
    {
    }

    /**
     * Test attribute "valor_original_titulo_cobranca"
     */
    public function testPropertyValorOriginalTituloCobranca()
    {
    }

    /**
     * Test attribute "valor_atual_titulo_cobranca"
     */
    public function testPropertyValorAtualTituloCobranca()
    {
    }

    /**
     * Test attribute "valor_pagamento_parcial_titulo"
     */
    public function testPropertyValorPagamentoParcialTitulo()
    {
    }

    /**
     * Test attribute "valor_abatimento_titulo_cobranca"
     */
    public function testPropertyValorAbatimentoTituloCobranca()
    {
    }

    /**
     * Test attribute "percentual_imposto_sobre_opr_financeiras_titulo_cobranca"
     */
    public function testPropertyPercentualImpostoSobreOprFinanceirasTituloCobranca()
    {
    }

    /**
     * Test attribute "valor_imposto_sobre_opr_financeiras_titulo_cobranca"
     */
    public function testPropertyValorImpostoSobreOprFinanceirasTituloCobranca()
    {
    }

    /**
     * Test attribute "valor_moeda_titulo_cobranca"
     */
    public function testPropertyValorMoedaTituloCobranca()
    {
    }

    /**
     * Test attribute "percentual_juro_mora_titulo"
     */
    public function testPropertyPercentualJuroMoraTitulo()
    {
    }

    /**
     * Test attribute "valor_juro_mora_titulo"
     */
    public function testPropertyValorJuroMoraTitulo()
    {
    }

    /**
     * Test attribute "percentual_multa_titulo"
     */
    public function testPropertyPercentualMultaTitulo()
    {
    }

    /**
     * Test attribute "valor_multa_titulo_cobranca"
     */
    public function testPropertyValorMultaTituloCobranca()
    {
    }

    /**
     * Test attribute "quantidade_parcela_titulo_cobranca"
     */
    public function testPropertyQuantidadeParcelaTituloCobranca()
    {
    }

    /**
     * Test attribute "data_baixa_automatico_titulo"
     */
    public function testPropertyDataBaixaAutomaticoTitulo()
    {
    }

    /**
     * Test attribute "texto_campo_utilizacao_cedente"
     */
    public function testPropertyTextoCampoUtilizacaoCedente()
    {
    }

    /**
     * Test attribute "indicador_cobranca_partilhado_titulo"
     */
    public function testPropertyIndicadorCobrancaPartilhadoTitulo()
    {
    }

    /**
     * Test attribute "nome_sacado_cobranca"
     */
    public function testPropertyNomeSacadoCobranca()
    {
    }

    /**
     * Test attribute "texto_endereco_sacado_cobranca"
     */
    public function testPropertyTextoEnderecoSacadoCobranca()
    {
    }

    /**
     * Test attribute "nome_bairro_sacado_cobranca"
     */
    public function testPropertyNomeBairroSacadoCobranca()
    {
    }

    /**
     * Test attribute "nome_municipio_sacado_cobranca"
     */
    public function testPropertyNomeMunicipioSacadoCobranca()
    {
    }

    /**
     * Test attribute "sigla_unidade_federacao_sacado_cobranca"
     */
    public function testPropertySiglaUnidadeFederacaoSacadoCobranca()
    {
    }

    /**
     * Test attribute "numero_cep_sacado_cobranca"
     */
    public function testPropertyNumeroCepSacadoCobranca()
    {
    }

    /**
     * Test attribute "valor_moeda_abatimento_titulo"
     */
    public function testPropertyValorMoedaAbatimentoTitulo()
    {
    }

    /**
     * Test attribute "data_protesto_titulo_cobranca"
     */
    public function testPropertyDataProtestoTituloCobranca()
    {
    }

    /**
     * Test attribute "codigo_tipo_inscricao_sacador"
     */
    public function testPropertyCodigoTipoInscricaoSacador()
    {
    }

    /**
     * Test attribute "numero_inscricao_sacador_avalista"
     */
    public function testPropertyNumeroInscricaoSacadorAvalista()
    {
    }

    /**
     * Test attribute "nome_sacador_avalista_titulo"
     */
    public function testPropertyNomeSacadorAvalistaTitulo()
    {
    }

    /**
     * Test attribute "percentual_desconto_titulo"
     */
    public function testPropertyPercentualDescontoTitulo()
    {
    }

    /**
     * Test attribute "data_desconto_titulo"
     */
    public function testPropertyDataDescontoTitulo()
    {
    }

    /**
     * Test attribute "valor_desconto_titulo"
     */
    public function testPropertyValorDescontoTitulo()
    {
    }

    /**
     * Test attribute "codigo_desconto_titulo"
     */
    public function testPropertyCodigoDescontoTitulo()
    {
    }

    /**
     * Test attribute "percentual_segundo_desconto_titulo"
     */
    public function testPropertyPercentualSegundoDescontoTitulo()
    {
    }

    /**
     * Test attribute "data_segundo_desconto_titulo"
     */
    public function testPropertyDataSegundoDescontoTitulo()
    {
    }

    /**
     * Test attribute "valor_segundo_desconto_titulo"
     */
    public function testPropertyValorSegundoDescontoTitulo()
    {
    }

    /**
     * Test attribute "codigo_segundo_desconto_titulo"
     */
    public function testPropertyCodigoSegundoDescontoTitulo()
    {
    }

    /**
     * Test attribute "percentual_terceiro_desconto_titulo"
     */
    public function testPropertyPercentualTerceiroDescontoTitulo()
    {
    }

    /**
     * Test attribute "data_terceiro_desconto_titulo"
     */
    public function testPropertyDataTerceiroDescontoTitulo()
    {
    }

    /**
     * Test attribute "valor_terceiro_desconto_titulo"
     */
    public function testPropertyValorTerceiroDescontoTitulo()
    {
    }

    /**
     * Test attribute "codigo_terceiro_desconto_titulo"
     */
    public function testPropertyCodigoTerceiroDescontoTitulo()
    {
    }

    /**
     * Test attribute "data_multa_titulo"
     */
    public function testPropertyDataMultaTitulo()
    {
    }

    /**
     * Test attribute "numero_carteira_cobranca"
     */
    public function testPropertyNumeroCarteiraCobranca()
    {
    }

    /**
     * Test attribute "numero_variacao_carteira_cobranca"
     */
    public function testPropertyNumeroVariacaoCarteiraCobranca()
    {
    }

    /**
     * Test attribute "quantidade_dia_protesto"
     */
    public function testPropertyQuantidadeDiaProtesto()
    {
    }

    /**
     * Test attribute "quantidade_dia_prazo_limite_recebimento"
     */
    public function testPropertyQuantidadeDiaPrazoLimiteRecebimento()
    {
    }

    /**
     * Test attribute "data_limite_recebimento_titulo"
     */
    public function testPropertyDataLimiteRecebimentoTitulo()
    {
    }

    /**
     * Test attribute "indicador_permissao_recebimento_parcial"
     */
    public function testPropertyIndicadorPermissaoRecebimentoParcial()
    {
    }

    /**
     * Test attribute "texto_codigo_barras_titulo_cobranca"
     */
    public function testPropertyTextoCodigoBarrasTituloCobranca()
    {
    }

    /**
     * Test attribute "codigo_ocorrencia_cartorio"
     */
    public function testPropertyCodigoOcorrenciaCartorio()
    {
    }

    /**
     * Test attribute "valor_imposto_sobre_opr_financeiras_recebido_titulo"
     */
    public function testPropertyValorImpostoSobreOprFinanceirasRecebidoTitulo()
    {
    }

    /**
     * Test attribute "valor_abatimento_total"
     */
    public function testPropertyValorAbatimentoTotal()
    {
    }

    /**
     * Test attribute "valor_juro_mora_recebido"
     */
    public function testPropertyValorJuroMoraRecebido()
    {
    }

    /**
     * Test attribute "valor_desconto_utilizado"
     */
    public function testPropertyValorDescontoUtilizado()
    {
    }

    /**
     * Test attribute "valor_pago_sacado"
     */
    public function testPropertyValorPagoSacado()
    {
    }

    /**
     * Test attribute "valor_credito_cedente"
     */
    public function testPropertyValorCreditoCedente()
    {
    }

    /**
     * Test attribute "codigo_tipo_liquidacao"
     */
    public function testPropertyCodigoTipoLiquidacao()
    {
    }

    /**
     * Test attribute "data_credito_liquidacao"
     */
    public function testPropertyDataCreditoLiquidacao()
    {
    }

    /**
     * Test attribute "data_recebimento_titulo"
     */
    public function testPropertyDataRecebimentoTitulo()
    {
    }

    /**
     * Test attribute "codigo_prefixo_dependencia_recebedor"
     */
    public function testPropertyCodigoPrefixoDependenciaRecebedor()
    {
    }

    /**
     * Test attribute "codigo_natureza_recebimento"
     */
    public function testPropertyCodigoNaturezaRecebimento()
    {
    }

    /**
     * Test attribute "numero_identidade_sacado_titulo_cobranca"
     */
    public function testPropertyNumeroIdentidadeSacadoTituloCobranca()
    {
    }

    /**
     * Test attribute "codigo_responsavel_atualizacao"
     */
    public function testPropertyCodigoResponsavelAtualizacao()
    {
    }

    /**
     * Test attribute "codigo_tipo_baixa_titulo"
     */
    public function testPropertyCodigoTipoBaixaTitulo()
    {
    }

    /**
     * Test attribute "valor_multa_recebido"
     */
    public function testPropertyValorMultaRecebido()
    {
    }

    /**
     * Test attribute "valor_reajuste"
     */
    public function testPropertyValorReajuste()
    {
    }

    /**
     * Test attribute "valor_outro_recebido"
     */
    public function testPropertyValorOutroRecebido()
    {
    }

    /**
     * Test attribute "codigo_indicador_economico_utilizado_inadimplencia"
     */
    public function testPropertyCodigoIndicadorEconomicoUtilizadoInadimplencia()
    {
    }
}
