<?php
/**
 * RespostaConsultaPixBoletoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cobranças API
 *
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.17.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * RespostaConsultaPixBoletoTest Class Doc Comment
 *
 * @category    Class
 * @description Representação dos campos de resposta de uma solicitação de detalhamento de pix vinculado a boleto bancário.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RespostaConsultaPixBoletoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "RespostaConsultaPixBoleto"
     */
    public function testRespostaConsultaPixBoleto()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "data_registro_titulo_cobranca"
     */
    public function testPropertyDataRegistroTituloCobranca()
    {
    }

    /**
     * Test attribute "agencia_beneficiario"
     */
    public function testPropertyAgenciaBeneficiario()
    {
    }

    /**
     * Test attribute "conta_beneficiario"
     */
    public function testPropertyContaBeneficiario()
    {
    }

    /**
     * Test attribute "valor_original_titulo_cobranca"
     */
    public function testPropertyValorOriginalTituloCobranca()
    {
    }

    /**
     * Test attribute "validade_titulo_cobranca"
     */
    public function testPropertyValidadeTituloCobranca()
    {
    }

    /**
     * Test attribute "pix"
     */
    public function testPropertyPix()
    {
    }

    /**
     * Test attribute "qr_code"
     */
    public function testPropertyQrCode()
    {
    }
}
