<?php
/**
 * BoletosApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cobranças API
 *
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.17.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BoletosApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BoletosApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for alteraBoletoBancarioId
     *
     * Altera um boleto bancário.
     *
     */
    public function testAlteraBoletoBancarioId()
    {
    }

    /**
     * Test case for boletosBaixaOperacional
     *
     * Informações de Baixa Operacional de Boletos.
     *
     */
    public function testBoletosBaixaOperacional()
    {
    }

    /**
     * Test case for cancelarPixBoletoId
     *
     * Cancelar Pix de Boleto.
     *
     */
    public function testCancelarPixBoletoId()
    {
    }

    /**
     * Test case for consultarPixBoletoId
     *
     * Consultar Pix de Boleto.
     *
     */
    public function testConsultarPixBoletoId()
    {
    }

    /**
     * Test case for detalhaBoletoBancarioId
     *
     * Detalha um boleto bancário.
     *
     */
    public function testDetalhaBoletoBancarioId()
    {
    }

    /**
     * Test case for gerarPixBoletoId
     *
     * Gerar Pix de Boleto.
     *
     */
    public function testGerarPixBoletoId()
    {
    }

    /**
     * Test case for incluiBoletoBancarioId
     *
     * Registra Boleto de Cobrança.
     *
     */
    public function testIncluiBoletoBancarioId()
    {
    }

    /**
     * Test case for listaBoletosId
     *
     * Lista Boletos.
     *
     */
    public function testListaBoletosId()
    {
    }

    /**
     * Test case for permitirBaixaCancelamentoId
     *
     * Permitir a baixa/cancelamento de um  título de cobrança..
     *
     */
    public function testPermitirBaixaCancelamentoId()
    {
    }
}
